name: trie_router
description: A Trie-based route parsing package
version: 1.0.1
homepage: https://github.com/johnpryan/trie_router

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dependencies:
  path: ^1.8.0-nullsafety.3
  quiver: ^3.0.0-nullsafety.3
  collection: ^1.15.0-nullsafety.5

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.17
